devices:
- device_type: cisco_ios_telnet
  host: 10.10.10.129
  location: Core
  name: R1
  role: core
  snmp_community: public
  zone: Core
- device_type: cisco_ios_telnet
  host: 10.10.10.2
  location: Core
  name: R2
  role: core
  snmp_community: public
  zone: Core
- device_type: cisco_ios_telnet
  host: 192.168.189.10
  location: Core
  name: R3
  role: core
  snmp_community: public
  zone: Core
- device_type: cisco_ios_telnet
  host: 192.168.189.20
  location: Core
  name: R4
  role: core
  snmp_community: public
  zone: Core
- device_type: cisco_ios_telnet
  host: 10.10.10.41
  location: Core
  name: R5
  role: core
  snmp_community: public
  zone: Core
