links:
  - source: ESW1
    source_port: FastEthernet0/0
    target: R5
    target_port: FastEthernet0/0
  - source: ESW1
    source_port: FastEthernet0/1
    target: PC1
    target_port: e0
  - source: ESW2
    source_port: FastEthernet0/0
    target: R1
    target_port: FastEthernet0/0
  - source: ESW2
    source_port: FastEthernet0/1
    target: PC2
    target_port: e0
  - source: R1
    source_port: Serial2/0
    target: R2
    target_port: Serial2/0
  - source: R2
    source_port: Serial2/1
    target: R5
    target_port: Serial2/0
  - source: R1
    source_port: Serial2/2
    target: R5
    target_port: Serial2/2
  - source: R1
    source_port: Serial2/1
    target: R3
    target_port: Serial2/1
  - source: R3
    source_port: Serial2/0
    target: R4
    target_port: Serial2/1
  - source: R4
    source_port: Serial2/0
    target: R5
    target_port: Serial2/1
